[package]
name = "tmp-mail"
version = "0.1.0"
authors = ["Mogeko <zhengjunyi@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
samotop = "0.12.0"
hostname = "0.3.1"
